// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldiijuyspyqkhwfzwjuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaWlqdXlzcHlxa2h3Znp3anVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTA2MjMsImV4cCI6MjA2ODQ4NjYyM30.hZiS8RGNtclTkt1xIzEZfOpKnMaUAcz4g4hyygBnfAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});